describe('Verificações', () => {
    it('Verificações e cadastro', () => {
       cy.visit("https://automationexercise.com/")

       cy.get(':nth-child(3) > .product-image-wrapper > .choose > .nav > li > a').click()
       cy.get('#quantity').clear()
       cy.get('#quantity').type(4)
       cy.get(':nth-child(5) > .btn').click()
       cy.get('u').click()
       cy.get('.active').should("have.text", "Shopping Cart")
       cy.get('h4 > a').should("have.text", "Blue Top")
       cy.get('.cart_description > p').should("have.text", "Women > Tops")
       cy.get('.cart_price > p').should("have.text", "Rs. 500")
       cy.get('.disabled').should("have.text", "4")
       cy.get('.cart_total_price').should("have.text", "Rs. 2000")
       cy.get('.col-sm-6 > .btn').click()
       cy.get('.modal-body > :nth-child(2) > a > u').click()//vai jogar para fazer login

       cy.get('[data-qa="signup-name"]').type("QaMarcusd336")
       cy.get('[data-qa="signup-email"]').type("qabpvassd336@gmail.com")
       cy.get('[data-qa="signup-button"]').click()
       cy.get('#id_gender1').click()
       cy.get('#id_gender2').click()
       cy.get('[data-qa="password"]').type("12121212")
       cy.get('[data-qa="days"]').select('25')
       cy.get('[data-qa="months"]').select('August')
       cy.get('[data-qa="years"]').select('2000')
       cy.get('#newsletter').click()
       cy.get('#optin').click()
       cy.get('[data-qa="first_name"]').type("QaDev21212")
       cy.get('[data-qa="last_name"]').type("Oliveira")
       cy.get('[data-qa="company"]').type("DMS")
       cy.get('[data-qa="address"]').type("Rua Barao Silva")
       cy.get('[data-qa="address2"]').type("Rua Doutor Silva")
       cy.get('[data-qa="country"]').select('Canada')
       cy.get('[data-qa="state"]').type("Ontario")
       cy.get('[data-qa="city"]').type("Toronto")
       cy.get('[data-qa="zipcode"]').type("123567890-90")
       cy.get('[data-qa="mobile_number"]').type("21999098778")
       cy.get('[data-qa="create-account"]').click()
       cy.get('b').should("have.text", "Account Created!")
       cy.get('[data-qa="continue-button"]').click()
       cy.get('b').should("have.text", "QaMarcusd336")
       cy.get('.shop-menu > .nav > :nth-child(3) > a').click()
       cy.get('.col-sm-6 > .btn').click()
       cy.get(':nth-child(2) > .heading').should("have.text", "Address Details")
       cy.get(':nth-child(4) > .heading').should("have.text", "Review Your Order")
       cy.get('.active').should("have.text", "Checkout")
       cy.get('h4 > a').should("have.text", "Blue Top")
       cy.get('.cart_description > p').should("have.text", "Women > Tops")
       cy.get('.cart_price > p').should("have.text", "Rs. 500")
       cy.get('.disabled').should("have.text", "4")
       cy.get('h4 > b').should("have.text", "Total Amount")
       cy.get(':nth-child(4) > .cart_total_price').should("have.text", "Rs. 2000")
       cy.get('.form-control').type("pipipippopopo")
       cy.get(':nth-child(7) > .btn').click()
       cy.get('[data-qa="name-on-card"]').type("Qadev Oliveira")
       cy.get('[data-qa="card-number"]').type("121232325252")
       cy.get('[data-qa="cvc"]').type("311")
       cy.get('[data-qa="expiry-month"]').type("12")
       cy.get('[data-qa="expiry-year"]').type("2025")
       cy.get('[data-qa="pay-button"]').click()
       cy.get('.col-sm-9 > p').should("have.text", "Congratulations! Your order has been confirmed!")
       cy.get(':nth-child(5) > a').click()
       cy.get('b').should("have.text", "Account Deleted!")

       //mudando test

       cy.contains(" Signup / Login").click()
       cy.get('[data-qa="signup-name"]').type("Gabigol222")
       cy.get('[data-qa="signup-email"]').type("gabi22gol@gmail.com")
       cy.get('[data-qa="signup-button"]').click()
       cy.get('#id_gender1').click()
       cy.get('#id_gender2').click()
       cy.get('[data-qa="password"]').type("12121212")
       cy.get('[data-qa="days"]').select('25')
       cy.get('[data-qa="months"]').select('August')
       cy.get('[data-qa="years"]').select('2000')
       cy.get('#newsletter').click()
       cy.get('#optin').click()
       cy.get('[data-qa="first_name"]').type("QaDev21212")
       cy.get('[data-qa="last_name"]').type("Oliveira")
       cy.get('[data-qa="company"]').type("DMS")
       cy.get('[data-qa="address"]').type("Rua Barao Silva")
       cy.get('[data-qa="address2"]').type("Rua Doutor Silva")
       cy.get('[data-qa="country"]').select('Canada')
       cy.get('[data-qa="state"]').type("Ontario")
       cy.get('[data-qa="city"]').type("Toronto")
       cy.get('[data-qa="zipcode"]').type("123567890-90")
       cy.get('[data-qa="mobile_number"]').type("21999098778")
       cy.get('[data-qa="create-account"]').click()
       cy.get('[data-qa="continue-button"]').click()
       cy.get('b').should("have.text", "Gabigol222")
       cy.get('.features_items > :nth-child(3) > .product-image-wrapper > .single-products > .productinfo > .btn').click()
       cy.get('u').click()
       cy.get('h4 > a').should("have.text", "Blue Top")
       cy.get('.cart_description > p').should("have.text", "Women > Tops")
       cy.get('.cart_price > p').should("have.text", "Rs. 500")
       cy.get('.disabled').should("have.text", "1")
       cy.get('.col-sm-6 > .btn').click()
       cy.get(':nth-child(2) > .heading').should("have.text", "Address Details")
       cy.get(':nth-child(4) > .heading').should("have.text", "Review Your Order")
       cy.get('.form-control').type("pipipopo")
       cy.get(':nth-child(7) > .btn').click()
       cy.get('[data-qa="name-on-card"]').type("Gabigol")
       cy.get('[data-qa="card-number"]').type("121232325252")
       cy.get('[data-qa="cvc"]').type("311")
       cy.get('[data-qa="expiry-month"]').type("12")
       cy.get('[data-qa="expiry-year"]').type("2025")
       cy.get('[data-qa="pay-button"]').click()
       cy.get('.col-sm-9 > p').should("have.text", "Congratulations! Your order has been confirmed!")
       cy.get(':nth-child(5) > a').click()
       cy.get('b').should("have.text", "Account Deleted!")
       
       //prox test

       cy.contains(" Signup / Login").click()
       cy.get('[data-qa="signup-name"]').type("Mvqabp12")
       cy.get('[data-qa="signup-email"]').type("mvqabp12@gmail.com")
       cy.get('[data-qa="signup-button"]').click()
       cy.get('#id_gender1').click()
       cy.get('#id_gender2').click()
       cy.get('[data-qa="password"]').type("12121212")
       cy.get('[data-qa="days"]').select('25')
       cy.get('[data-qa="months"]').select('August')
       cy.get('[data-qa="years"]').select('2000')
       cy.get('#newsletter').click()
       cy.get('#optin').click()
       cy.get('[data-qa="first_name"]').type("QaDev21212")
       cy.get('[data-qa="last_name"]').type("Oliveira")
       cy.get('[data-qa="company"]').type("DMS")
       cy.get('[data-qa="address"]').type("Rua Barao Silva")
       cy.get('[data-qa="address2"]').type("Rua Doutor Silva")
       cy.get('[data-qa="country"]').select('Canada')
       cy.get('[data-qa="state"]').type("Ontario")
       cy.get('[data-qa="city"]').type("Toronto")
       cy.get('[data-qa="zipcode"]').type("123567890-90")
       cy.get('[data-qa="mobile_number"]').type("21999098778")
       cy.get('[data-qa="create-account"]').click()
       cy.get('[data-qa="continue-button"]').click()
       cy.get('.shop-menu > .nav > :nth-child(4) > a').click()
       cy.contains("Home").click()
       cy.get('.features_items > :nth-child(3) > .product-image-wrapper > .single-products > .productinfo > .btn').click()
       cy.get('u').click()
       cy.get('h4 > a').should("have.text", "Blue Top")
       cy.get('.cart_description > p').should("have.text", "Women > Tops")
       cy.get('.cart_price > p').should("have.text", "Rs. 500")
       cy.get('.disabled').should("have.text", "1")
       cy.get('.col-sm-6 > .btn').click()
       cy.get('.modal-body > :nth-child(2) > a > u').click() //fazer login para seguir a compra
       cy.get('[data-qa="login-email"]').type("mvqabp12@gmail.com")
       cy.get('[data-qa="login-password"]').type("12121212")
       cy.get('[data-qa="login-button"]').click()
       cy.contains("Cart").click()
       cy.get('.col-sm-6 > .btn').click()
       cy.get(':nth-child(2) > .heading').should("have.text", "Address Details")
       cy.get(':nth-child(4) > .heading').should("have.text", "Review Your Order")
       cy.get('.form-control').type("pipipopo")
       cy.get(':nth-child(7) > .btn').click()
       cy.get('[data-qa="name-on-card"]').type("Mvbp")
       cy.get('[data-qa="card-number"]').type("121232325252")
       cy.get('[data-qa="cvc"]').type("311")
       cy.get('[data-qa="expiry-month"]').type("12")
       cy.get('[data-qa="expiry-year"]').type("2025")
       cy.get('[data-qa="pay-button"]').click()
       cy.get('.col-sm-9 > p').should("have.text", "Congratulations! Your order has been confirmed!")
       cy.get(':nth-child(5) > a').click()
       cy.get('b').should("have.text", "Account Deleted!")

       //prox test

       cy.contains("Home").click()
       cy.get('.features_items > :nth-child(3) > .product-image-wrapper > .single-products > .productinfo > .btn').click()
       cy.get('u').click()
       cy.get('.cart_delete').click()
       cy.get('b').should("have.text", "Cart is empty!")

       //pro test

       cy.contains("Home").click()
       cy.get('.left-sidebar > :nth-child(1)').should("have.text", "Category")
       cy.get(':nth-child(1) > .panel-heading > .panel-title > a > .badge > .fa').click()
       cy.contains("Dress").click
       cy.get(':nth-child(2) > .panel-heading > .panel-title > .collapsed > .badge > .fa').click()
       cy.contains("Tshirts").click()
       






    });
});