describe('Download', () => {
    it('Download e criação', () => {
        
        cy.visit("https://automationexercise.com/")
        cy.get('.features_items > :nth-child(3) > .product-image-wrapper > .single-products > .productinfo > .btn').click()
        cy.get('u').click()
        cy.get('.col-sm-6 > .btn').click()
        cy.get('.modal-body > :nth-child(2) > a > u').click()
        cy.get('[data-qa="signup-name"]').type("Nanimv702222222")
        cy.get('[data-qa="signup-email"]').type("nani22mv70222227222122@gmail.com")
        cy.get('[data-qa="signup-button"]').click()
        cy.get('#id_gender1').click()
        cy.get('#id_gender2').click()
        cy.get('[data-qa="password"]').type("12121212")
        cy.get('[data-qa="days"]').select('25')
        cy.get('[data-qa="months"]').select('August')
        cy.get('[data-qa="years"]').select('2000')
        cy.get('#newsletter').click()
        cy.get('#optin').click()
        cy.get('[data-qa="first_name"]').type("QaDev21212")
        cy.get('[data-qa="last_name"]').type("Oliveira")
        cy.get('[data-qa="company"]').type("DMS")
        cy.get('[data-qa="address"]').type("Rua Barao Silva")
        cy.get('[data-qa="address2"]').type("Rua Doutor Silva")
        cy.get('[data-qa="country"]').select('Canada')
        cy.get('[data-qa="state"]').type("Ontario")
        cy.get('[data-qa="city"]').type("Toronto")
        cy.get('[data-qa="zipcode"]').type("123567890-90")
        cy.get('[data-qa="mobile_number"]').type("21999098778")
        cy.get('[data-qa="create-account"]').click()
        cy.get('[data-qa="account-created"]').should("have.text", "Account Created!")
        cy.get('[data-qa="continue-button"]').click()
        cy.get('b').should("have.text", "Nanimv702222222")
        cy.get('.shop-menu > .nav > :nth-child(3) > a').click()
        cy.get('.col-sm-6 > .btn').click()
        cy.get(':nth-child(2) > .heading').should("have.text", "Address Details")
        cy.get('.form-control').type("pipipipipopopo")
        cy.get(':nth-child(7) > .btn').click()
        cy.get('[data-qa="name-on-card"]').type("mvmvmvqa")
        cy.get('[data-qa="card-number"]').type("1235678")
        cy.get('[data-qa="cvc"]').type("211")
        cy.get('[data-qa="expiry-month"]').type("11")
        cy.get('[data-qa="expiry-year"]').type("2025")
        cy.get('[data-qa="pay-button"]').click()
        cy.get('.col-sm-9 > p').should("have.text", "Congratulations! Your order has been confirmed!")
        cy.downloadFile("https://automationexercise.com/download_invoice/400")
        cy.get('[data-qa="continue-button"]').click()
        cy.get('.shop-menu > .nav > :nth-child(5) > a').click()
        cy.get('b').should("have.text", "Account Deleted!")
        cy.get('[data-qa="continue-button"]').click()



    });
});