describe('Navegação', () => {
    it('Testar funcionamento da page', () => {
        cy.visit("https://automationexercise.com/")

        cy.contains("Test Cases").click()
        cy.get('b').should("have.text", "Test Cases")


        cy.contains("Products").click()
        cy.get('.title').should("have.text", "All Products")
        cy.get(':nth-child(3) > .product-image-wrapper > .choose > .nav > li > a').click()
        cy.get('.product-information > h2').should("have.text", "Blue Top")
        cy.get('.product-information > :nth-child(3)').should("have.text", "Category: Women > Tops")
        cy.get(':nth-child(5) > span').should("have.text", "Rs. 500")
        cy.get('.product-information > :nth-child(6)').should("have.text", "Availability: In Stock")
        cy.get('.product-information > :nth-child(7)').should("have.text", "Condition: New")
        cy.get('.product-information > :nth-child(8)').should("have.text", "Brand: Polo")
        cy.contains("Products").click()
        cy.get('#search_product').type("winter")
        cy.get('#submit_search').click()
        cy.get('.title').should("have.text", "Searched Products")
        cy.get('.productinfo > p').should("have.text", "Winter Top")

        cy.contains("Home").click()
        cy.get('.single-widget > h2').should("have.text", "Subscription")
        cy.get('#susbscribe_email').type("qadev22@gmail.com")
        cy.get('#subscribe').click()
        cy.get('.alert-success').should("have.text", "You have been successfully subscribed!")

        cy.contains("Cart").click()
        cy.get('.single-widget > h2').should("have.text", "Subscription")
        cy.get('#susbscribe_email').type("qadev22@gmail.com")
        cy.get('#subscribe').click()
        cy.get('.alert-success').should("have.text", "You have been successfully subscribed!")

        cy.get(':nth-child(4) > a').click()
        cy.get('[data-qa="signup-name"]').type("QabpMarcus1")
        cy.get('[data-qa="signup-email"]').type("qabpvass1@gmail.com")
        cy.get('[data-qa="signup-button"]').click()
        cy.get('#id_gender1').click()
        cy.get('#id_gender2').click()
        cy.get('[data-qa="password"]').type("12121212")
        cy.get('[data-qa="days"]').select('25')
        cy.get('[data-qa="months"]').select('August')
        cy.get('[data-qa="years"]').select('2000')
        cy.get('#newsletter').click()
        cy.get('#optin').click()
        cy.get('[data-qa="first_name"]').type("QaDev21212")
        cy.get('[data-qa="last_name"]').type("Oliveira")
        cy.get('[data-qa="company"]').type("DMS")
        cy.get('[data-qa="address"]').type("Rua Barao Silva")
        cy.get('[data-qa="address2"]').type("Rua Doutor Silva")
        cy.get('[data-qa="country"]').select('Canada')
        cy.get('[data-qa="state"]').type("Ontario")
        cy.get('[data-qa="city"]').type("Toronto")
        cy.get('[data-qa="zipcode"]').type("123567890-90")
        cy.get('[data-qa="mobile_number"]').type("21999098778")
        cy.get('[data-qa="create-account"]').click()
        cy.get('[data-qa="continue-button"]').click()

        cy.contains("Products").click()
        cy.get(':nth-child(3) > .product-image-wrapper > .single-products > .productinfo > .btn').click()
        cy.get('.modal-footer > .btn').click()
        cy.get(':nth-child(4) > .product-image-wrapper > .single-products > .productinfo > .btn').click()
        cy.get('.modal-footer > .btn').click()
        cy.get('.shop-menu > .nav > :nth-child(3) > a').click()
        cy.get('#product-1 > .cart_description > h4 > a').should("have.text" , "Blue Top")
        cy.get('#product-1 > .cart_price > p').should("have.text", "Rs. 500") 
        cy.get('#product-1 > .cart_quantity > .disabled').should("have.text", "1") 
        cy.get('#product-1 > .cart_total > .cart_total_price').should("have.text", "Rs. 500") 
        cy.get('#product-2 > .cart_description > h4 > a').should("have.text", "Men Tshirt") 
        cy.get('#product-2 > .cart_price > p').should("have.text", "Rs. 400") 
        cy.get('#product-2 > .cart_quantity > .disabled').should("have.text", "1") 
        cy.get('#product-2 > .cart_total > .cart_total_price').should("have.text", "Rs. 400") 

        cy.get('.shop-menu > .nav > :nth-child(5) > a').click() //conta deletada
        cy.get('[data-qa="continue-button"]').click()
    });
});